### ISSUE TITLE
Please add the "move" box on Sourceforge to inform

### ISSUE THREAD

**Issue by Neustradamus** [WinMerge/frhed#8]
Dear WinMerge and frhed devs, @kimmov, @gerundt,

In first, I wish you a Happy New Year.

It will be nice to remove old parts like:
- https://sourceforge.net/p/frhed/wiki/Home/
- Please import into GitHub: https://sourceforge.net/p/frhed/feature-requests/
- Please import into GitHub: https://sourceforge.net/p/frhed/bugs/

There are spams in:
- https://sourceforge.net/p/frhed/bugs/

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/frhed/

To disable/delete tabs, go here: https://sourceforge.net/projects/frhed/
To add a new tab, go here: https://sourceforge.net/projects/frhed/
To change informations, go here: https://sourceforge.net/p/frhed/admin/overview
To export, go here: https://sourceforge.net/p/frhed/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/frhed/admin/overview
- "Preferred Support Page (for users of your project)", here: https://sourceforge.net/p/frhed/admin/overview
- A new tab, go here: https://sourceforge.net/projects/frhed/

Thanks in advance.

**Comment by sdottaka** [comment]
This repository is just a fork of https://bitbucket.org/jtuc/frhed (https://github.com/datadiode/frhed), not an official one.

**Comment by Neustradamus** [comment]
@sdottaka: It is for the continuity, it is important.

I have request to @kimmov, Kimmo Varis (Old leader):
https://sourceforge.net/p/frhed/_members/

Please reopen it, it is not solved.

**Comment by sdottaka** [comment]
The frhed in this repository is a fork of frhed (https://github.com/datadiode/frhed) used by WinMerge2011, so it should be called a fork of fork. 
At least https://github.com/datadiode/frhed has been updated to 2021, so it's not appropriate here.

**Comment by Neustradamus** [comment]
master from this repo: https://github.com/WinMerge/frhed/commits/master

datadiode master: https://github.com/datadiode/frhed/commits?author=sdottaka

It is possible to look changes and merge all since your commit from Commits on Feb 8, 2015 (less than 2 pages):
- https://github.com/datadiode/frhed/commits/master
